set(CPACK_PACKAGE_VENDOR Gawrjuschin)
set(CPACK_PACKAGE_CONTACT "Dmitriy Gavryushin <nihsuyrvag@gmail.com>")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_RESOURCE_FILE_LICENSE ${PROJECT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${PROJECT_SOURCE_DIR}/README.md)
set(CPACK_VERBATIM_VARIABLES ON)
set(CPACK_STRIP_FILES ON)

include(CPack)
