#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_DDS_IMPLEMENTATION
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include <stb_image_resize.h>
#include <stb_image.h>
#include <stb_image_dds.h>

#undef STB_IMAGE_IMPLEMENTATION
#undef STB_IMAGE_DDS_IMPLEMENTATION
#undef STB_IMAGE_RESIZE_IMPLEMENTATION
